import { Link } from "react-router-dom";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useStore } from "../context/StoreContext";

export default function Cart(){
 const {cart,subtotal,updateQty,removeFromCart}=useStore(); const shipping=subtotal>100||subtotal===0?0:9.99; const tax=subtotal*.08; const total=subtotal+shipping+tax;
 if(!cart.length)return <section className="container-app py-24 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-brand-50 text-brand-600 dark:bg-brand-950"><ShoppingBag size={34}/></div><h1 className="mt-6 text-3xl font-black">Your cart is empty</h1><p className="mt-2 text-slate-500">Looks like you haven't added anything yet.</p><Link to="/products" className="btn-primary mt-6">Start shopping</Link></section>;
 return <section className="container-app py-10"><h1 className="text-4xl font-black">Shopping cart</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{cart.map(x=><div key={x.id} className="card flex gap-4 p-4"><img src={x.thumbnail} className="h-24 w-24 rounded-xl bg-slate-100 object-contain p-2 dark:bg-slate-800"/><div className="min-w-0 flex-1"><h2 className="font-bold">{x.title}</h2><p className="mt-1 text-sm text-slate-500">${x.price.toFixed(2)} each</p><div className="mt-3 flex items-center gap-3"><div className="flex items-center rounded-lg border border-slate-200 dark:border-slate-700"><button onClick={()=>updateQty(x.id,x.qty-1)} className="p-2"><Minus size={14}/></button><span className="w-7 text-center text-sm font-bold">{x.qty}</span><button onClick={()=>updateQty(x.id,x.qty+1)} className="p-2"><Plus size={14}/></button></div><button onClick={()=>removeFromCart(x.id)} className="text-sm font-semibold text-rose-500"><Trash2 size={15} className="inline mr-1"/>Remove</button></div></div><b className="text-lg">${(x.price*x.qty).toFixed(2)}</b></div>)}</div><Summary subtotal={subtotal} shipping={shipping} tax={tax} total={total}/></div></section>
}
function Summary({subtotal,shipping,tax,total}){return <aside className="card h-fit p-6"><h2 className="text-xl font-black">Order summary</h2><div className="mt-5 space-y-3 text-sm"><Row l="Subtotal" v={`$${subtotal.toFixed(2)}`}/><Row l="Shipping" v={shipping?"$9.99":"Free"}/><Row l="Tax" v={`$${tax.toFixed(2)}`}/><div className="border-t border-slate-200 pt-4 dark:border-slate-700"><Row l="Total" v={`$${total.toFixed(2)}`} bold/></div></div><Link to="/checkout" className="btn-primary mt-6 w-full">Proceed to checkout</Link><p className="mt-3 text-center text-xs text-slate-400">Secure checkout • Free shipping over $100</p></aside>}
function Row({l,v,bold}){return <div className={`flex justify-between ${bold?"text-base font-black":"text-slate-500"}`}><span>{l}</span><span className={bold?"text-slate-900 dark:text-white":""}>{v}</span></div>}