import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Lock, ShieldCheck } from "lucide-react";
import { useStore } from "../context/StoreContext";

export default function Checkout(){
 const {cart,subtotal,clearCart}=useStore(); const navigate=useNavigate(); const [errors,setErrors]=useState({}); const [loading,setLoading]=useState(false);
 const shipping=subtotal>100?0:9.99; const tax=subtotal*.08; const total=subtotal+shipping+tax;
 if(!cart.length)return <div className="container-app py-24 text-center"><h1 className="text-3xl font-black">Nothing to checkout</h1><Link to="/products" className="btn-primary mt-5">Continue shopping</Link></div>;
 const submit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const required=["firstName","lastName","email","address","city","postal","card"];const er={};required.forEach(k=>{if(!data[k]?.trim())er[k]="This field is required"});if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))er.email="Enter a valid email";if(data.postal&&!/^\d{5}$/.test(data.postal))er.postal="Use a 5-digit ZIP code";if(data.card&&!/^\d{16}$/.test(data.card.replace(/\s/g,"")))er.card="Enter a valid 16-digit card number";setErrors(er);if(Object.keys(er).length)return;setLoading(true);setTimeout(()=>{clearCart();navigate("/success")},900)};
 return <section className="container-app py-10"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-brand-600">Secure checkout</p><h1 className="mt-1 text-4xl font-black">Complete your order</h1></div><form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="card p-6 md:p-8"><Section title="Contact information"><div className="grid gap-4 md:grid-cols-2"><Field name="firstName" label="First name" error={errors.firstName}/><Field name="lastName" label="Last name" error={errors.lastName}/><Field name="email" label="Email" type="email" error={errors.email}/></div></Section><Section title="Shipping address"><div className="grid gap-4 md:grid-cols-2"><Field name="address" label="Street address" error={errors.address} full/><Field name="city" label="City" error={errors.city}/><Field name="postal" label="ZIP code" error={errors.postal}/></div></Section><Section title="Payment"><Field name="card" label="Card number" placeholder="4242 4242 4242 4242" error={errors.card}/><div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Lock size={14}/> Demo payment only — no real transaction is processed.</div></Section><button disabled={loading} className="btn-primary mt-7 w-full">{loading?"Processing...":<>Place order · ${total.toFixed(2)}</>}</button></div><aside className="card h-fit p-6"><h2 className="font-black">Order total</h2><div className="mt-5 space-y-3 text-sm"><Row l="Subtotal" v={`$${subtotal.toFixed(2)}`}/><Row l="Shipping" v={shipping?"$9.99":"Free"}/><Row l="Tax" v={`$${tax.toFixed(2)}`}/><Row l="Total" v={`$${total.toFixed(2)}`} bold/></div><div className="mt-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"><ShieldCheck className="mb-2" size={20}/><b>Safe checkout</b><p className="mt-1">Your demo order information stays in this browser.</p></div></aside></form></section>
}
function Section({title,children}){return <div className="border-b border-slate-200 pb-7 pt-2 first:pt-0 dark:border-slate-800"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</div>}
function Field({name,label,type="text",placeholder,error,full}){return <label className={`block ${full?"md:col-span-2":""}`}><span className="mb-1.5 block text-sm font-semibold">{label}</span><input name={name} type={type} placeholder={placeholder} className={`input ${error?"border-rose-500 focus:border-rose-500":""}`}/>{error&&<span className="mt-1 block text-xs font-semibold text-rose-500">{error}</span>}</label>}
function Row({l,v,bold}){return <div className={`flex justify-between ${bold?"border-t border-slate-200 pt-4 text-base font-black dark:border-slate-700":"text-slate-500"}`}><span>{l}</span><span>{v}</span></div>}